logpath: './logs'
batch_date_path: "/home/deck/devlopment/litestardemo/batch_date.txt"


defaults:
  - _self_
  - db@remote_dev: heavy
  - api@hold_place_dev: place_holder

  - env@remote_dev: dev
  - env@hold_place_dev: dev

  - db_env@remote_dev: "${db@remote_dev}_${env@remote_dev}"
  - api_env@hold_place_dev: "${api@hold_place_dev}_${env@hold_place_dev}"


