# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application



on:
  workflow_dispatch:
    inputs:
      text_input:
        description: 'Enter a text value'
        required: true
        type: text
      boolean_input:
        description: 'Toggle this boolean input'
        required: false
        type: boolean
      choice_input:
        description: 'Select one option'
        required: true
        type: choice
        options:
          - Option1
          - Option2
          - Option3

jobs:
  show_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Print Inputs
        run: |
          echo "Text Input: ${{ github.event.inputs.text_input }}"
          echo "Boolean Input: ${{ github.event.inputs.boolean_input }}"
          echo "Choice Selected: ${{ github.event.inputs.choice_input }}"

